doc-warnings: true

test-warnings: false

strictness: medium

max-line-length: 80

ignore-paths:
    - tests
    - scripts

python-targets:
    - 2
    - 3

pep8:
    full: true

pep257:
    disable:
        - D203
